apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: drone-simulator
  labels:
    app: drone-simulator
spec:
  rules:
  - host: drone-simulator.local
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: drone-simulator
            port:
              number: 80
